permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : Atmega328P Adventure Hour
author :
  github : bitfighter

production_url : http://bitfighter.github.io

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments :
    provider : false
  analytics :
    provider : false
  sharing :
    provider : false
